env: JRUBY_OPTS=--debug
language: ruby

cache:
  bundler: true

script:
  - make test

notifications:
  email:
    holidaysgem@gmail.com

rvm:
  - 2.4.5
  - jruby-9.0.5.0
  - 2.5.3
  - 2.6.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
